Option Explicit On 
Option Strict On
Option Infer On

Namespace Windows.Forms

Public Class HtmlEditorControl

Inherits System.Windows.Forms.UserControl

#Region " Vom Windows Form Designer generierter Code "
Private WithEvents mainEditorControl As SSP.MyPage.Windows.Forms.EditorControl
Private WithEvents mainSplitContainer As System.Windows.Forms.SplitContainer
Private WithEvents mainHtmlEditor As SpiceLogic.WinHTMLEditor.HTMLEditor
    ' Für Windows Form-Designer erforderlich
    Private components As System.ComponentModel.IContainer

    'HINWEIS: Die folgende Prozedur ist für den Windows Form-Designer erforderlich
    'Sie kann mit dem Windows Form-Designer modifiziert werden.
    'Verwenden Sie nicht den Code-Editor zur Bearbeitung.
    <System.Diagnostics.DebuggerStepThrough()> Private Sub InitializeComponent()
Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(HtmlEditorControl))
Me.mainHtmlEditor = New SpiceLogic.WinHTMLEditor.HTMLEditor()
Me.mainSplitContainer = New System.Windows.Forms.SplitContainer()
Me.mainEditorControl = New SSP.MyPage.Windows.Forms.EditorControl()
CType(Me.mainHtmlEditor, System.ComponentModel.ISupportInitialize).BeginInit()
Me.mainHtmlEditor.SuspendLayout()
CType(Me.mainSplitContainer, System.ComponentModel.ISupportInitialize).BeginInit()
Me.mainSplitContainer.Panel1.SuspendLayout()
Me.mainSplitContainer.Panel2.SuspendLayout()
Me.mainSplitContainer.SuspendLayout()
Me.SuspendLayout()
'
'mainHtmlEditor
'
Me.mainHtmlEditor.AutoScrollMargin = New System.Drawing.Size(0, 0)
Me.mainHtmlEditor.AutoScrollMinSize = New System.Drawing.Size(0, 0)
Me.mainHtmlEditor.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink
Me.mainHtmlEditor.BackgroundImagePath = ""
Me.mainHtmlEditor.BaseUrl = ""
Me.mainHtmlEditor.BodyColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
Me.mainHtmlEditor.BodyHtml = Nothing
Me.mainHtmlEditor.BodyStyle = Nothing
Me.mainHtmlEditor.Charset = "unicode"
Me.mainHtmlEditor.Cursor = System.Windows.Forms.Cursors.Default
Me.mainHtmlEditor.DefaultForeColor = System.Drawing.Color.Black
Me.mainHtmlEditor.Dock = System.Windows.Forms.DockStyle.Fill
Me.mainHtmlEditor.DocumentHtml = resources.GetString("mainHtmlEditor.DocumentHtml")
Me.mainHtmlEditor.DocumentTitle = ""
Me.mainHtmlEditor.EditorContextMenuStrip = Nothing
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_New", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "New", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "New", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Open", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Open", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems1"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Open", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Save", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Save", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems2"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Save", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(26, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator1", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Font Name", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Font Name", Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Verdana", 8.0!), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(160, 24)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Font Size", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Font Size", Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator2", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Cut", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Cut", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems3"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Cut", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(26, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Copy", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Copy", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems4"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Copy", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(27, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Paste", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Paste", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems5"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Paste", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(27, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator3", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Bold", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Bold", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems6"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Bold", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Italic", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Italic", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems7"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Italic", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Underline", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Underline", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems8"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Underline", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Horizontal Rule", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Horizontal Rule", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems9"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Horizontal Rule", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Format Reset", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Format Reset", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems10"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Format Reset", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(34, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Undo", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Undo", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems11"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Undo", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Redo", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Redo", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems12"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Redo", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Edit Source", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Edit Source", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems13"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Edit Source", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(34, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Spell Check", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, True, True, True, True, "Spell Check", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems14"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Spell Check", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Title Insert", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Title Insert", Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(105, 29)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Text Highlight Color", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Text Highlight Color", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems15"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Text Highlight Color", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Font Color", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Font Color", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems16"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Font Color", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator4", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_HyperLink", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "HyperLink", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems17"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "HyperLink", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Image", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Image", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems18"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Image", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator5", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Insert Ordered List", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Insert Ordered List", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems19"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Insert Ordered List", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Insert Unordered List", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Insert Unordered List", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems20"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Insert Unordered List", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator6", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Left", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Left", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems21"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Left", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(26, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Center", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Center", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems22"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Center", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(26, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Right", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Right", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems23"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Right", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(26, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator7", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Table", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Table", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems24"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Table", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator8", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Outdent", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Outdent", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems25"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Outdent", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Indent", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Indent", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems26"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Indent", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator9", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, Nothing, Nothing, System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, Nothing, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(0, 0)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Strike through", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Strike through", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems27"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Strike through", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(24, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_SuperScript", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "SuperScript", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems28"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "SuperScript", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(27, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Subscript", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Subscript", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems29"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Subscript", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(27, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Body Style", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Body Style", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems30"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Body Style", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(34, 26)))
Me.mainHtmlEditor.FactoryToolbarItems.Add(New SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Print", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, True, True, True, True, "Print", CType(resources.GetObject("mainHtmlEditor.FactoryToolbarItems31"), System.Drawing.Image), System.Drawing.Color.Empty, Nothing, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Print", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, New System.Drawing.Size(23, 26)))
Me.mainHtmlEditor.LicenseKey = "2F69-9E26-FC12-7DFB-D167-2A8E-83D6-60B5"
Me.mainHtmlEditor.Location = New System.Drawing.Point(0, 0)
Me.mainHtmlEditor.Name = "mainHtmlEditor"
Me.mainHtmlEditor.ScrollBars = SpiceLogic.WinHTMLEditor.ScrollBarVisibility.[Default]
Me.mainHtmlEditor.Size = New System.Drawing.Size(332, 383)
'
'
'
Me.mainHtmlEditor.SpellCheckDictionary.DictionaryFile = "de-DE.dic"
'
'
'
Me.mainHtmlEditor.SpellChecker.Dictionary = Me.mainHtmlEditor.SpellCheckDictionary
Me.mainHtmlEditor.TabIndex = 0
'
'mainHtmlEditor.HtmlEditorToolbar1
'
Me.mainHtmlEditor.Toolbar1.GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden
Me.mainHtmlEditor.Toolbar1.Location = New System.Drawing.Point(0, 0)
Me.mainHtmlEditor.Toolbar1.Name = "HtmlEditorToolbar1"
Me.mainHtmlEditor.Toolbar1.Size = New System.Drawing.Size(332, 27)
Me.mainHtmlEditor.Toolbar1.TabIndex = 0
Me.mainHtmlEditor.Toolbar1.Text = "toolStrip1"
'
'mainHtmlEditor.HtmlEditorToolbar2
'
Me.mainHtmlEditor.Toolbar2.GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden
Me.mainHtmlEditor.Toolbar2.Location = New System.Drawing.Point(0, 27)
Me.mainHtmlEditor.Toolbar2.Name = "HtmlEditorToolbar2"
Me.mainHtmlEditor.Toolbar2.Size = New System.Drawing.Size(332, 29)
Me.mainHtmlEditor.Toolbar2.TabIndex = 1
Me.mainHtmlEditor.Toolbar2.Text = "toolStrip2"
Me.mainHtmlEditor.ToolbarContextMenuStrip = Nothing
Me.mainHtmlEditor.ToolbarCursor = System.Windows.Forms.Cursors.Default
'
'mainSplitContainer
'
Me.mainSplitContainer.Dock = System.Windows.Forms.DockStyle.Fill
Me.mainSplitContainer.Location = New System.Drawing.Point(0, 0)
Me.mainSplitContainer.Name = "mainSplitContainer"
'
'mainSplitContainer.Panel1
'
Me.mainSplitContainer.Panel1.Controls.Add(Me.mainHtmlEditor)
'
'mainSplitContainer.Panel2
'
Me.mainSplitContainer.Panel2.Controls.Add(Me.mainEditorControl)
Me.mainSplitContainer.Size = New System.Drawing.Size(648, 383)
Me.mainSplitContainer.SplitterDistance = 332
Me.mainSplitContainer.TabIndex = 1
'
'mainEditorControl
'
Me.mainEditorControl.Dock = System.Windows.Forms.DockStyle.Fill
Me.mainEditorControl.Location = New System.Drawing.Point(0, 0)
Me.mainEditorControl.Name = "mainEditorControl"
Me.mainEditorControl.Padding = New System.Windows.Forms.Padding(4)
Me.mainEditorControl.Size = New System.Drawing.Size(312, 383)
Me.mainEditorControl.TabIndex = 2
'
'HtmlEditorControl
'
Me.Controls.Add(Me.mainSplitContainer)
Me.Name = "HtmlEditorControl"
Me.Size = New System.Drawing.Size(648, 383)
CType(Me.mainHtmlEditor, System.ComponentModel.ISupportInitialize).EndInit()
Me.mainHtmlEditor.ResumeLayout(False)
Me.mainHtmlEditor.PerformLayout()
Me.mainSplitContainer.Panel1.ResumeLayout(False)
Me.mainSplitContainer.Panel2.ResumeLayout(False)
CType(Me.mainSplitContainer, System.ComponentModel.ISupportInitialize).EndInit()
Me.mainSplitContainer.ResumeLayout(False)
Me.ResumeLayout(False)

End Sub

#End Region

#Region " --------------->> Enumerationen der Klasse "
  '{Enumerationen}
#End Region '{Enumerationen der Klasse}

#Region " --------------->> Eigenschaften der Klasse "
  '{Eigenschaften}
#End Region '{Eigenschaften der Klasse}

#Region " --------------->> Konstruktor und Destruktor der Klasse "
  '{Konstruktor/ Destruktor}
  Public Sub New()
  '{Konstruktor}
  MyBase.New()
    InitializeComponent()
    mainHtmlEditor.XHTMLMode = True
    mainEditorControl.commandsToolStrip.Items.Add _
    (New ToolStripButton("Html in Editor übertragen" _
    , Nothing, AddressOf onSetBodyHtlm))
  End Sub

  ' Die Form überschreibt den Löschvorgang der Basisklasse, um Komponenten zu bereinigen.
  Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
    If disposing Then
      If Not (components Is Nothing) Then components.Dispose()
    End If
    MyBase.Dispose(disposing)
  End Sub
#End Region '{Konstruktor und Destruktor der Klasse}

#Region " --------------->> Zugriffsmethoden der Klasse "
  '{Zugrifsmethoden}
#End Region '{Zugriffsmethoden der Klasse}

#Region " --------------->> Ereignismethoden Methoden der Klasse "
  '{Ereignismethoden}
#End Region '{Private Ereignismethoden der Klasse}

#Region " --------------->> Private Methoden der Klasse "
  '{Private Methoden}
#End Region '{Private Methoden der Klasse}

#Region " --------------->> Öffentliche Methoden der Klasse "
  '{Öffentliche Methoden}
#End Region 'Öffentliche Methoden der Klasse}


  Private Sub onHtmlChanged _
  (ByVal sender As System.Object _
  , ByVal e As SpiceLogic.WinHTMLEditor.HtmlChangedEventArgs) _
  Handles mainHtmlEditor.HtmlChanged

    mainEditorControl.Text = e.NewDocumentText
  End Sub

  Private Sub onSetBodyHtlm _
  (ByVal sender As Object _
  , ByVal e As System.EventArgs)
    mainHtmlEditor.BodyHtml = mainEditorControl.Text
  End Sub

End Class '{Klasse HtmlEditorDialog}
End Namespace
